import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { ArrowDownRight, ArrowUpRight, Bot, BriefcaseBusiness, Check, CircleDollarSign, Clock3, Download, Gauge, Search, Sparkles, Target } from "lucide-react";
import { Logo } from "@/components/logo";
import { ReportActions } from "@/components/report-nav";
import { ScoreRing } from "@/components/score-ring";
import { getRepository } from "@/lib/repository";
import { formatCurrency, formatDate } from "@/lib/utils";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const { id } = await params; const audit = await getRepository().get(id); return { title: audit ? `${audit.company_name} AI Audit` : "Audit report" }; }

export default async function AuditReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const audit = await getRepository().get(id); if (!audit) notFound(); if (audit.status !== "completed") redirect(`/audit/${id}/processing`);
  const opps = audit.opportunities ?? []; const total = opps.reduce((sum, x) => sum + x.monthly_roi, 0); const hours = opps.reduce((sum, x) => sum + x.hours_saved, 0); const now = opps.filter((x) => x.priority === "Now");
  return <main className="min-h-screen bg-[#f5f4ef] print:bg-white">
    <header className="sticky top-0 z-40 border-b border-black/10 bg-[#f5f4ef]/90 backdrop-blur-xl print:hidden"><div className="mx-auto flex h-20 max-w-[1450px] items-center justify-between px-6 lg:px-10"><Logo /><div className="hidden text-center md:block"><div className="text-xs font-semibold">{audit.company_name} / AI efficiency audit</div><div className="mt-1 text-[10px] uppercase tracking-[.15em] text-black/35">Prepared {formatDate(audit.created_at)}</div></div><ReportActions pdfUrl={`/api/audits/${id}/pdf`} /></div></header>

    <section className="noise relative overflow-hidden bg-ink text-white"><div className="grid-bg absolute inset-0" /><div className="absolute -right-32 -top-20 size-[580px] rounded-full bg-cobalt/25 blur-[120px]" /><div className="relative mx-auto max-w-[1450px] px-6 py-20 lg:px-10 lg:py-28"><div className="mb-16 flex items-center justify-between text-xs uppercase tracking-[.16em] text-white/35"><span>Confidential opportunity assessment</span><span>NS–{audit.id.slice(0, 7).toUpperCase()}</span></div><div className="grid items-end gap-12 lg:grid-cols-[1fr_360px]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-white/55"><Sparkles size={13} className="text-lime" /> AI transformation brief</div><h1 className="display text-[clamp(4rem,8vw,8rem)] leading-[.84]">{audit.company_name}</h1><p className="display mt-3 text-4xl text-lime md:text-6xl">Efficiency audit.</p></div><p className="pb-2 text-lg leading-8 text-white/55">A quantified view of the AI, automation, and digital growth opportunities hiding inside the current business.</p></div></div></section>

    <section className="relative z-10 mx-auto -mt-5 grid max-w-[1370px] gap-px overflow-hidden rounded-[24px] bg-black/10 shadow-soft md:grid-cols-4 print:mt-0 print:shadow-none">{[
      [CircleDollarSign, formatCurrency(total, true), "Monthly value identified"], [Clock3, String(hours), "Hours reclaimed / month"], [Gauge, `${audit.seo?.seo_score}/100`, "SEO opportunity score"], [Target, String(now.length), "Start-now priorities"],
    ].map(([Icon, value, label]) => { const MetricIcon = Icon as typeof Gauge; return <div key={String(label)} className="bg-white p-7"><MetricIcon size={18} className="mb-10 text-cobalt" /><div className="display text-4xl">{String(value)}</div><div className="mt-2 text-xs uppercase tracking-[.13em] text-black/40">{String(label)}</div></div>; })}</section>

    <div className="mx-auto max-w-[1250px] px-6 py-20 lg:px-10 lg:py-28">
      <section className="grid gap-12 border-b border-black/10 pb-24 lg:grid-cols-[280px_1fr]"><div><div className="text-xs font-bold uppercase tracking-[.17em] text-cobalt">01 / Executive readout</div></div><div><h2 className="display text-5xl leading-[.95] md:text-7xl">The opportunity, in plain English.</h2><p className="mt-9 max-w-4xl text-xl leading-9 text-black/60">{audit.executive_summary}</p><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-white p-6"><BriefcaseBusiness className="mb-8 text-cobalt" /><div className="text-xs uppercase tracking-wider text-black/35">Business model</div><p className="mt-2 font-semibold leading-6">{audit.profile?.business_model}</p></div><div className="rounded-2xl bg-white p-6"><Target className="mb-8 text-cobalt" /><div className="text-xs uppercase tracking-wider text-black/35">Primary audience</div><p className="mt-2 font-semibold leading-6">{audit.profile?.target_audience}</p></div></div></div></section>

      <section className="grid gap-12 border-b border-black/10 py-24 lg:grid-cols-[280px_1fr]"><div><div className="text-xs font-bold uppercase tracking-[.17em] text-cobalt">02 / Business profile</div></div><div><h2 className="display text-5xl">What we see.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-black/55">{audit.profile?.company_summary}</p><div className="mt-12 grid gap-10 md:grid-cols-2"><div><h3 className="mb-5 text-sm font-bold">Core services</h3><div className="flex flex-wrap gap-2">{audit.profile?.services.map((x) => <span key={x} className="rounded-full border border-black/10 bg-white px-3 py-2 text-sm">{x}</span>)}</div></div><div><h3 className="mb-5 text-sm font-bold">Likely operating friction</h3><ul className="space-y-3">{audit.profile?.pain_points.map((x) => <li key={x} className="flex gap-3 text-sm text-black/60"><ArrowDownRight size={16} className="mt-0.5 shrink-0 text-cobalt" />{x}</li>)}</ul></div></div></div></section>

      <section className="grid gap-12 border-b border-black/10 py-24 lg:grid-cols-[280px_1fr]"><div><div className="text-xs font-bold uppercase tracking-[.17em] text-cobalt">03 / Website & SEO</div></div><div><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><h2 className="display text-5xl">Search readiness.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-black/50">A directional assessment of technical foundations, visible content, and the journey from search to conversion.</p></div><div className="flex gap-1"><ScoreRing score={audit.seo?.seo_score ?? 0} label="overall" /><ScoreRing score={audit.seo?.technical_score ?? 0} label="technical" /><ScoreRing score={audit.seo?.content_score ?? 0} label="content" /></div></div><div className="mt-14 divide-y divide-black/10 border-y border-black/10">{audit.seo?.findings.map((item, i) => <article key={item.title} className="grid gap-5 py-7 md:grid-cols-[45px_1fr_110px]"><span className="font-mono text-xs text-black/30">0{i + 1}</span><div><h3 className="font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-black/50">{item.detail}</p></div><span className={`h-fit w-fit rounded-full px-3 py-1 text-[10px] font-bold uppercase ${item.impact === "high" ? "bg-orange-100 text-orange-800" : "bg-black/5 text-black/50"}`}>{item.impact} impact</span></article>)}</div></div></section>

      <section className="grid gap-12 border-b border-black/10 py-24 lg:grid-cols-[280px_1fr]"><div><div className="text-xs font-bold uppercase tracking-[.17em] text-cobalt">04 / Competitive view</div><p className="mt-4 text-xs leading-5 text-black/35">Directional hypotheses for strategic discovery—not live competitor scraping.</p></div><div><h2 className="display text-5xl">Where the market leaves room.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{audit.competitors?.map((item) => <article key={item.competitor_name} className="rounded-2xl border border-black/10 bg-white p-6"><div className="mb-10 flex items-center justify-between"><span className="grid size-9 place-items-center rounded-full bg-black/5"><Search size={15} /></span><ArrowUpRight size={16} className="text-black/25" /></div><h3 className="display text-2xl">{item.competitor_name}</h3><div className="mt-7 text-[10px] font-bold uppercase tracking-wider text-black/35">Their edge</div><p className="mt-2 text-sm leading-6 text-black/55">{item.strengths.join(" · ")}</p><div className="mt-6 text-[10px] font-bold uppercase tracking-wider text-cobalt">Your opening</div><p className="mt-2 text-sm leading-6 text-black/55">{item.opportunities.join(" · ")}</p></article>)}</div></div></section>

      <section className="grid gap-12 border-b border-black/10 py-24 lg:grid-cols-[280px_1fr]"><div><div className="text-xs font-bold uppercase tracking-[.17em] text-cobalt">05 / Automation portfolio</div><p className="mt-4 text-xs leading-5 text-black/35">Value estimates combine monthly capacity savings and modeled revenue opportunity.</p></div><div><div className="flex flex-wrap items-end justify-between gap-6"><h2 className="display text-5xl">The work to redesign.</h2><span className="rounded-full bg-lime px-4 py-2 text-xs font-bold">{opps.length} opportunities</span></div><div className="mt-12 space-y-3">{opps.map((item, i) => <article key={item.problem} className="group rounded-2xl border border-black/10 bg-white p-6 transition hover:border-cobalt/30 hover:shadow-lg hover:shadow-black/5"><div className="grid gap-5 md:grid-cols-[38px_1fr_150px]"><span className="font-mono text-xs text-black/25">{String(i + 1).padStart(2, "0")}</span><div><div className="mb-3 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider ${item.priority === "Now" ? "bg-cobalt text-white" : "bg-black/5 text-black/50"}`}>{item.priority}</span><span className="rounded-full border border-black/10 px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider text-black/45">{item.category}</span></div><h3 className="text-lg font-semibold tracking-tight">{item.problem}</h3><p className="mt-2 text-sm leading-6 text-black/50">{item.solution}</p><div className="mt-5 flex flex-wrap gap-5 text-xs text-black/40"><span>{item.hours_saved} hrs/mo</span><span>{item.implementation_difficulty} complexity</span><span>{formatCurrency(item.annual_roi)} annual value</span></div></div><div className="md:text-right"><div className="display text-3xl text-cobalt">{formatCurrency(item.monthly_roi, true)}</div><div className="mt-1 text-[10px] uppercase tracking-wider text-black/35">monthly upside</div></div></div></article>)}</div></div></section>

      <section className="grid gap-12 py-24 lg:grid-cols-[280px_1fr]"><div><div className="text-xs font-bold uppercase tracking-[.17em] text-cobalt">06 / Recommended roadmap</div></div><div><h2 className="display text-5xl">Move in three deliberate waves.</h2><div className="mt-14 space-y-4">{audit.roadmap?.map((item, i) => <article key={item.period} className="grid overflow-hidden rounded-2xl bg-ink text-white md:grid-cols-[180px_1fr]"><div className={`${i === 0 ? "bg-cobalt" : "bg-white/5"} p-7`}><div className="text-xs font-bold uppercase tracking-wider text-white/50">Wave {i + 1}</div><div className="display mt-3 text-3xl">{item.period}</div></div><div className="p-7"><h3 className="text-xl font-semibold">{item.title}</h3><ul className="mt-5 grid gap-3 md:grid-cols-3">{item.actions.map((x) => <li key={x} className="flex gap-2 text-sm leading-6 text-white/55"><Check size={15} className="mt-1 shrink-0 text-lime" />{x}</li>)}</ul></div></article>)}</div></div></section>
    </div>
    <section className="bg-cobalt text-white print:hidden"><div className="mx-auto flex max-w-[1250px] flex-col items-start justify-between gap-8 px-6 py-16 md:flex-row md:items-center lg:px-10"><div><div className="text-xs font-bold uppercase tracking-[.15em] text-white/50">Take this into the room</div><h2 className="display mt-3 text-4xl">Your complete report is ready.</h2></div><a href={`/api/audits/${id}/pdf`} className="inline-flex items-center gap-3 rounded-full bg-lime px-6 py-4 text-sm font-bold text-ink transition hover:-translate-y-1"><Download size={17} /> Download the consulting PDF</a></div></section>
  </main>;
}
