import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, CheckCircle2, CircleDollarSign, Clock3, FileText, Search, Sparkles } from "lucide-react";
import type { AuditRecord } from "@/lib/types";
import { formatCurrency, formatDate } from "@/lib/utils";

export function AdminDashboard({ audits, total, page, search, status, aggregate }: { audits: AuditRecord[]; total: number; page: number; search: string; status: string; aggregate: AuditRecord[] }) {
  const completed = aggregate.filter((x) => x.status === "completed").length; const pending = aggregate.filter((x) => !["completed", "failed"].includes(x.status)).length; const value = aggregate.flatMap((x) => x.opportunities ?? []).reduce((sum, x) => sum + x.monthly_roi, 0); const pages = Math.max(1, Math.ceil(total / 8));
  const query = (patch: Record<string, string | number>) => `?${new URLSearchParams({ search, status, page: String(page), ...Object.fromEntries(Object.entries(patch).map(([k, v]) => [k, String(v)])) })}`;
  return <main className="min-h-screen bg-[#f3f3ef]">
    <aside className="fixed inset-y-0 left-0 hidden w-64 flex-col bg-ink p-7 text-white lg:flex"><Link href="/" className="flex items-center gap-2.5 font-semibold"><span className="grid size-8 place-items-center rounded-full border border-white/20 bg-white/10"><span className="size-2.5 rotate-45 bg-lime" /></span>Northstar<span className="-ml-2 text-white/40">/AI</span></Link><nav className="mt-16 space-y-2 text-sm"><span className="flex items-center gap-3 rounded-xl bg-white/10 px-4 py-3"><Sparkles size={16} className="text-lime" /> Audit intelligence</span><a href="/api/health" className="flex items-center gap-3 rounded-xl px-4 py-3 text-white/40 hover:bg-white/5 hover:text-white"><CheckCircle2 size={16} /> System health</a></nav><div className="mt-auto rounded-2xl border border-white/10 bg-white/5 p-4"><div className="text-[10px] uppercase tracking-wider text-white/35">Operator note</div><p className="mt-2 text-xs leading-5 text-white/50">ROI is modeled opportunity, not booked revenue. Qualify it before sales use.</p></div></aside>
    <div className="lg:pl-64"><header className="border-b border-black/10 bg-white/60 px-6 py-5 backdrop-blur-xl lg:px-10"><div className="flex items-center justify-between"><div><div className="text-xs text-black/40">Workspace / Audits</div><h1 className="display mt-1 text-3xl">Efficiency intelligence</h1></div><Link href="/" className="inline-flex items-center gap-2 rounded-full bg-ink px-4 py-2.5 text-xs font-semibold text-white">New audit <ArrowUpRight size={14} /></Link></div></header>
      <div className="p-6 lg:p-10"><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[
        [FileText, aggregate.length, "Total audits", "All time"], [Clock3, pending, "In progress", "Current queue"], [CheckCircle2, completed, "Reports generated", `${aggregate.length ? Math.round(completed / aggregate.length * 100) : 0}% completion`], [CircleDollarSign, formatCurrency(value, true), "Monthly upside", "Across reports"],
      ].map(([Icon, valueText, label, note]) => { const StatIcon = Icon as typeof FileText; return <article key={String(label)} className="rounded-2xl border border-black/[.08] bg-white p-5"><div className="flex items-start justify-between"><div><div className="text-xs text-black/40">{String(label)}</div><div className="display mt-3 text-4xl">{String(valueText)}</div></div><span className="grid size-9 place-items-center rounded-full bg-black/[.04]"><StatIcon size={16} /></span></div><div className="mt-7 text-[10px] uppercase tracking-wider text-black/30">{String(note)}</div></article>; })}</section>

        <section className="mt-6 overflow-hidden rounded-2xl border border-black/[.08] bg-white"><div className="flex flex-col justify-between gap-4 border-b border-black/[.08] p-5 md:flex-row md:items-center"><div><h2 className="font-semibold">Audit history</h2><p className="mt-1 text-xs text-black/40">Search, filter, and open generated client reports.</p></div><form className="flex flex-wrap gap-2"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-black/30" size={14} /><input name="search" defaultValue={search} placeholder="Search company or email" className="h-10 w-60 rounded-lg border border-black/10 bg-[#f7f7f4] pl-9 pr-3 text-xs outline-none focus:border-cobalt" /></label><select name="status" defaultValue={status} className="h-10 rounded-lg border border-black/10 bg-[#f7f7f4] px-3 text-xs outline-none"><option value="all">All statuses</option><option value="completed">Completed</option><option value="queued">Queued</option><option value="failed">Failed</option></select><button className="h-10 rounded-lg bg-ink px-4 text-xs font-semibold text-white">Apply</button></form></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-black/[.07] text-[10px] uppercase tracking-wider text-black/35"><th className="px-5 py-4 font-semibold">Company</th><th className="px-5 py-4 font-semibold">Status</th><th className="px-5 py-4 font-semibold">Created</th><th className="px-5 py-4 font-semibold">Opportunities</th><th className="px-5 py-4 font-semibold">Monthly value</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-black/[.06]">{audits.map((audit) => { const roi = audit.opportunities?.reduce((sum, x) => sum + x.monthly_roi, 0) ?? 0; return <tr key={audit.id} className="group text-sm transition hover:bg-black/[.015]"><td className="px-5 py-4"><div className="font-semibold">{audit.company_name}</div><div className="mt-1 text-xs text-black/35">{audit.email}</div></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${audit.status === "completed" ? "bg-emerald-50 text-emerald-700" : audit.status === "failed" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{audit.status}</span></td><td className="px-5 py-4 text-xs text-black/50">{formatDate(audit.created_at)}</td><td className="px-5 py-4 font-mono text-xs">{audit.opportunities?.length ?? "—"}</td><td className="px-5 py-4 font-semibold">{roi ? formatCurrency(roi) : "—"}</td><td className="px-5 py-4 text-right">{audit.status === "completed" && <Link href={`/audit/${audit.id}`} className="inline-flex items-center gap-1 text-xs font-semibold text-cobalt">Open <ArrowUpRight size={13} /></Link>}</td></tr>; })}{audits.length === 0 && <tr><td colSpan={6} className="px-5 py-16 text-center text-sm text-black/40">No audits match these filters.</td></tr>}</tbody></table></div>
          <div className="flex items-center justify-between border-t border-black/[.08] p-5 text-xs text-black/40"><span>Page {page} of {pages} · {total} results</span><div className="flex gap-2"><Link aria-disabled={page <= 1} href={page > 1 ? query({ page: page - 1 }) : "#"} className={`grid size-9 place-items-center rounded-lg border border-black/10 ${page <= 1 ? "pointer-events-none opacity-30" : "hover:bg-black/5"}`}><ArrowLeft size={14} /></Link><Link aria-disabled={page >= pages} href={page < pages ? query({ page: page + 1 }) : "#"} className={`grid size-9 place-items-center rounded-lg border border-black/10 ${page >= pages ? "pointer-events-none opacity-30" : "hover:bg-black/5"}`}><ArrowRight size={14} /></Link></div></div>
        </section>
      </div>
    </div>
  </main>;
}
